---
# Source: vaultwarden/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden
  namespace: vaultwarden
  labels:
    app.kubernetes.io/component: vaultwarden
    helm.sh/chart: vaultwarden-0.35.1
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/version: "1.35.4"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  YUBICO_SECRET_KEY: ""
  DUO_SKEY: ""
  PUSH_INSTALLATION_ID: ""
  PUSH_INSTALLATION_KEY: ""
  ADMIN_TOKEN: ""
