---
# Source: vaultwarden/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
  namespace: vaultwarden
  labels:
    app.kubernetes.io/component: vaultwarden
    helm.sh/chart: vaultwarden-0.43.0
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/version: "1.36.0"
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: vaultwarden
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: vaultwarden
      app.kubernetes.io/name: vaultwarden
      app.kubernetes.io/instance: vaultwarden
  template:
    metadata:
      labels:
        app.kubernetes.io/component: vaultwarden
        app.kubernetes.io/name: vaultwarden
        app.kubernetes.io/instance: vaultwarden
      annotations:
        checksum/config: 46ec03f11583a3196e9509a6a2c2379d4f51416e
        checksum/secret: e3f98a1ce15a8849eb732463c2601a8719f606f4
    spec:
      
      containers:
        - image: docker.io/vaultwarden/server:1.36.0-alpine
          imagePullPolicy: IfNotPresent
          name: vaultwarden
          envFrom:
            - configMapRef:
                name: vaultwarden
          env:
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-smtp-secret
                  key: smtp-username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-smtp-secret
                  key: smtp-password
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vaultwarden
                  key: ADMIN_TOKEN
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - name: vaultwarden-pvc
              mountPath: /data
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
          livenessProbe:
            httpGet:
              path: /alive
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /alive
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
      serviceAccountName: vaultwarden-svc
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  volumeClaimTemplates:
    - metadata:
        name: vaultwarden-pvc
        labels:
          app.kubernetes.io/component: vaultwarden
          app.kubernetes.io/name: vaultwarden
          app.kubernetes.io/instance: vaultwarden
        annotations:
          meta.helm.sh/release-name: "vaultwarden"
          meta.helm.sh/release-namespace: "vaultwarden"
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi

