apiVersion: v1
kind: ConfigMap
metadata:
  name: shlink-cm
data:
  DEFAULT_DOMAIN: link.nasus.dev
  IS_HTTPS_ENABLED: "true"
  DB_DRIVER: postgres
  DB_NAME: shlink
  DB_HOST: shlink-postgres-rw
  MEMORY_LIMIT: 200M
