apiVersion: apps/v1
kind: Deployment
metadata:
  name: shlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shlink
  template:
    metadata:
      labels:
        app: shlink
    spec:
      containers:
        - name: shlink
          image: shlinkio/shlink:4.4
          envFrom:
            - configMapRef:
                name: shlink-cm
            - secretRef:
                name: shlink-secret
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /rest/health
              port: http
          resources:
            requests:
              memory: "200Mi"
              cpu: "10m"
            limits:
              memory: "200Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shlink-web-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shlink-web-client
  template:
    metadata:
      labels:
        app: shlink-web-client
    spec:
      containers:
        - name: shlink-web-client
          image: shlinkio/shlink-web-client:4.4
          env:
            - name: SHLINK_SERVER_URL
              value: https://link.nasus.dev
            - name: SHLINK_SERVER_NAME
              value: link.nasus.dev
            - name: SHLINK_SERVER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shlink-secret
                  key: INITIAL_API_KEY
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "10Mi"
