apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bots-meetup
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: https://github.com/Nasus20202/cluster-argocd.git
    targetRevision: main
    path: apps/bots/meetup
  destination:
    name: in-cluster
    namespace: bots
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
