apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3
  storage:
    size: 1Gi
  resources:
    requests:
      cpu: 25m
      memory: 125Mi
    limits:
      memory: 250Mi
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: pg-authentik
