---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ralphkaminski-secret
spec:
  encryptedData:
    TOKEN: AgCfOyjxDBZfWg6SDxaupFy3l2YAe0azWef39WhCXcY0LEEHEYcedMBtJFpq21iXmz+9Vt2BSbUB/23JYLd5mdCqzRHzDphIUyuChk5fyPTJrXSzy/oxjt0HpMNq+ZnNetTnFKSWI9PM0wsTTBUfB8z9IlZ465QTNU+SECGpewZ+yI3f1NlPxrBljLw+fBAlDg7xq7/EYyt3R36eq0WsYYg3Q/HugrVNehcToFw5WGD7doKyDMq2ZBptiuxHICYedwObILmSp/0/zPzX3fhqofI7ErOnxzYOJPkPqj3p/Yqjpe5CP3fQjy+/7SEMMDLV+2Q4ai+xQIW/fOTSRdkXLG31NnIXfn8fg5QLUIEMHeRIFMPbgQYixJyqj2DAjJM5YJo2sMpzOSaasYZUMRTLibaaleuAs4JjXJC2eaFP4LNEzNPbsuAh+8HNH4cVccF+ZJDHjCeHqjGSP2BsKPPp9oVLyYYDx88Kc04yy9QUxRNNgDCOHRYnJwl/9o4cTUr8GoQTAjO5IZpMGNjMZ3vkHASVqZLExbAK3SulOe4X0ji7G9/+r97NzBTOHGp7cKypJ4BXzRvZ4gguMN1+eqSwj/cOtMUl5SJ+w6RQKihJiETvm3vc/+5WG1G7hcQBYk8R9qsY5fKXBx9kAAy2sdBXVf/OOTMgC0NKDtGSI+eGDT5a9vW6hr4lrw+1+YHG8TPgmojJw/S8RzF4r/nbZvj6I8CbUbn4vEBSsrywcw44TfI/o+EUFHr0z56kyTYWINnSA3MCUdQFbzc617vrmgd+GTzxTTsbKEpEkGY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ralphkaminski-secret
