---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pg-nextcloud
spec:
  encryptedData:
    password: AgAzcMqcRDwifY6qie34xkJf8ylJzCbbqQaDLjt6P0A2kfmw6I38RpWAuCwwi2tCAQOS62cej80wbvlnQuZXTovtOc/1n4aKN9+icXnbQHOaFV7xLnDXoBImjAWnZbOeXq1/eCz44cNgpRjM8eA3jKhctFp1D+rIaKwva9uSRWMweH+j4hIrSSj2T0F7g7BwRyV8rs+a4U0+cf65GexoKUyEAfNVu/rsbpf28/1tOKxYr3izjAXfXFDEcc6OJLBS+0BIpFUOb/X32dHDWX9lrQOELjxXUOW8r7jQT6g36Fx5jnQ9T/bRGfCWn5jwiZXmdG7Etajqbxs5FkqaPa5g/O4WOat7Q1zWDK3yn3RnwROeS8NEBdynVpQM1HcW8YMNXCQbVevqbT/y5ckIZgtuGAaewnW+/VI33L9kke1FDUa8NkRYryNfr/joVNK5yqjlCq7WRaCXwDxH5N1JljjzdYP9oRfPaR+JAVSuMbkhiQyEF6gn/MCjCgqq1q7RGadi1Toaw5N/j5hIzZwmShGmJLiMvUiNaVzv/8gm+1L+3Jje3lTe/q7SvcYEb3nORD6RhxKcptCNTOzfBN4ryRern081IdlAHVX4ELETkAzyqdLeM6bgnTn4Hr6ZaTSSaMy3EAjkgv0yxuYmFVKWRbKal6e9fBL1wxRTySGviSNp43ZvFFCL+5li+qDUeBp3Mn/y5f0Tv9pQHXFc5ep1JJA=
    username: AgBYLPFXe7QeiTXrkVgbUduBBU+5wDPbUpO5BGsyGugz/LdyGWt+o3q6L8TDLfIM26+RfzdhZQB1BbmpyWR/Bkp2EXnPgtz8lqPQoaZE8TUoQ8cdzw9puEIkZ4TyKJjJW8DNWWwtTSXBORKqkaP8eCzGgPSYiLMzI7IwYRnNxCfyZXZNKgVKu0m/qQCE/R43qAN+DBUpV27N3mtpHxxM8agXoSOMZIw2QhF4RT1kiQtYQHqpc6w/A7x6oArHDskmMkzKfJBEljRLOkgjJWYdpmf+YLgiHEMFJJI66A/juF1vY2DDAwM8N40XAYturwfFeOYxTGra8XIt3l5s5LGOxOPQ73D5E4veKh+XeoU6aKMufpmyHYTssSC4wuo5pBLd7+YwwnqCePPKk3uZvMjpQFpMGXOvnYr3vyx8iEC6HMlGFPrPhZt9al13Fn/f+I3/rR/xziliOEG6CTbG5tjzp9YDe4+ojEWTp8p6erBM6RsMNbiFu+uMVgYJOPb1JyFU2UKVqbmcRcKmv+Z4ZNlZZOxpbA9p16/4FRd0eBDJPX/iyWPHb+gTeT70+MYj5qjiUCpur1cZTOkIMC+zJTPkYyHPuZwoU/JUKbwiGeT2GGoTsF2phyt3F3b/nfsvq4lbmueWVCZ7zf0swM1+A2qtPpT67+DvmIhHa8rf3Jyw+Alh09TV3r5P0Mpgkxu4VLaiC9k6vOXDlm+Hkxk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pg-nextcloud
    type: kubernetes.io/basic-auth
