apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: "0.27.1"
      helm:
        valueFiles:
          - $values/apps/cloudnative-pg/values.yaml
    - repoURL: https://github.com/Nasus20202/cluster-argocd.git
      targetRevision: main
      ref: values
  destination:
    name: in-cluster
    namespace: cloudnative-pg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
