authentik:
  postgresql:
    host: postgres-postgresql.postgres
    name: authentik
    user: authentik
  email:
    host: smtp.purelymail.com
    port: 465
    username: sso@nasus.dev
    use_ssl: true
    from: "Nasus SSO <sso@nasus.dev>"

server:
  envFrom:
    - secretRef:
        name: authentik-secret-key
    - secretRef:
        name: authentik-db-secret
    - secretRef:
        name: authentik-smtp-secret
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - sso.nasus.dev
    tls:
      - hosts:
          - sso.nasus.dev
        secretName: authentik-tls
  metrics: # For some reason, I also had to manually set the scrape_protocols to ["PrometheusText0.0.4"]
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      memory: 750Mi
      cpu: 25m

worker:
  envFrom:
    - secretRef:
        name: authentik-secret-key
    - secretRef:
        name: authentik-db-secret
    - secretRef:
        name: authentik-smtp-secret
  resources:
    requests:
      memory: 500Mi
      cpu: 50m

redis:
  enabled: true
  master:
    kind: Deployment
    persistence:
      enabled: false
    resources:
      requests:
        memory: 50Mi
        cpu: 25m
