---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: leaguebot-secret
spec:
  encryptedData:
    DISCORD_TOKEN: AgASWwcpjqXUEMsb746lZYHSqTUnO/2PGmVm6j8FH/VLZhse97nzGjSCDg/otIhGumxzyJLixW/lKQxlMXNElSX0yA7VZxVM3M4XWnnEBcqidtaoGCIiYOruzICC02pu/dEbHSBR28jwBwZvqOOmCUZPXSaqnWqmBSKIYAeQPNz8rQQ0yMK9ScX8lNeIWe2l2qYHjxGIScVMJPXaluwZzHbgN9Pv+6jgSh8iPpo3HyBV34wiA95gaO2JwXTSSezVD/pCLQ0mBRnQNEsXunrlaG6OJALdoZG+VHXYkRYVW2ZUXkOgr+4EiZbIaX7l7aZ3acj/hIAJZzzOkn/+oEJhq9TF8yifRlYGFZB/6CrBBajmWpiBSCPtHmDurUKGBBjc015q9NrOAlcYUxVu2z02KsfbdzEpvrddLL6BRgKNxu0QdABdB1JtQ3i7Z5DSp5iUxQHVZZ19G1KOdXL9Lo2mZB/Wq8fCQkcXyJsFdFYwyMCvT4Tp8+oBxmIfyvL71EhaYrtmTOED84I6dIwBjxZaQG50wzi6Rtba7cQapVs3gxIk/FlTbAr421pSJsoX6rCDVdSqb0psRXwLBuh12gxnX/qQpjW8Gv7N4OBbIGIki/73c0Px+v4B35SWQm2gvMn2WePWlvKz/FxRNQBcKf1yRIaevG5YTHrkJTOZ1U2+friFKmd7KUdLnegRijhTX0dpjU9EJDLMipWmIwHkY4w1Kb192WQd4Jr+wH/LgYtwEy+XPhP/vnlRtowY8ICu8N4iD1V+1jlwnZm/ucCG6aaPKNneg0a5pxti
    RIOT_TOKEN: AgBaQvtR2Ybo8sy86Zfq8BY3GPgCfOuI1r/gV4MakSmfI7TkJw54rUP+lFa+ShLrKclnvXkQ4BuxGMSyg3Aa31BolbqIPS1tOo6sCJkYmBINmbExQNZN2CkkI3hF/SfvV3/MejYVeGtWKg6uef0W3D3OjZbqGb0IUt8azA0p75QKB8eQVZpnA5Dc1tA/2nu0oMlyhhuYE1I8MA1Azy+iJDJ4VXd8DzHAy35IXJtFdIcDIP+tINUurqSCCWM6r80N5zyNOLNCB56MjSA9l4ekndmBdxtnpJl3hk3IfHGP2Nn5thh1Ec7IRpNXghNfmfkC65XCQWm+eAbnwAAkVJm5xeCAlr+TmfGRbYos2c//Pm2TeQ9zu7ti4ww6EFdiJKDezoz+vNxfSIUpWUbdN70w3raIcYI9dkfqZpSzjBrUpsbnExRC08h1MFQ1PQeue7bpmMuwIuTGxUKuvT2ReJICT5lVq94+DDlMJoDzyVS+NbTD4GG3spjcpqjz9NLj5MvRud4QD0Tiia1xMNBczVTo7mIFkYkg2v6swlM6I+K61U1O0uOBO3vSAh8oHtYqvVxtlz5pBngTCeArRXP+O6ZR8NVrhzvoWyKvqqysVy5xP7BdK1Tn9SKAzmEUWrIyPed0Tn3SdxzCd9HaHNj7yRhV40TRQIPwN5fLFV6A6u09QD3NeqJFlyA+NTHBUOA3HXrRZ+tjZd7ZPl1KxeWEv92W0Y0RlyCNR67oK83tKQTzJjOojt0p3ns1AXqFras=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: leaguebot-secret
