---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: vaultwarden-admin-secret
spec:
  encryptedData:
    admin-token: AgAW0UH4m6rXBcorZnqFiEQVvKi5EeXok+mdQ3brV6WZe6iDJ9bL+lw2SypCxBBWQ3RYgizFTHsCQ7tntp8y+ULDOX3fJR+Bu01BBYMDj/q3scgCs5EVb/Wcru19f/EtEXYnlRxqogRpr8kn0RCz45szzvlDcCmJ+MJRu3vy1axoOCtcqZ4TGaf7Ve+L9wPOS46zIanMrK7EqCZB8lcisx7IjNIigUfOqpeR0b7DHP45fqMVkuJRT52KN/vzUdDXtEAKq8V+0Un+MiF0oqDgrUJrC6owEDyzv8MJ4ku0DlQnpm6erQesccOtpqwoS/gzWa+xIPLo62/ZDaYIR4TGFSK7H6UbY6fTrs6a1pyb42zbCRaoI/tzD0Q1kVEa190WliRqYJJuq4F74WXgnghKi8Q8ZJPbGjw9Y9uZ4pgosyUIFHpGtE8uVFG5s5oYuvhbGbUrVsRdTtcnXTqV1gHtyorbG9fY7vQwkoRUVksFng8Erdz9bYhM9+KTyWiDA2uRq0rZPZCnRRyvKylvLfUSnVbgKDg51hHKvUXu42VlaSUMpFFOMSdsKy8TbktAnVIXVSmkDPsfUubBeOjzF/8CxShRU+8lnkMDDC12bgO4d/6mD+QQrwXnLTUBe1W53Rm9aoDDDWoZjat8UpJ43JEJMfz2vL2EfayM2c2c2NyrtlazUfmhfCa7HkKOG84qvwdZvWHVkXsi7yvifwApV6QOwU4AWxXeJ5UkAob01/TocExYIZy0rswBqRxe+OKFG5nu30ix0GuGEVFmk+3buGbaKMNDycP/kw8M+LyknHbScydWdC4yzkT1QqVMiEI0xWUVRFX4wjL9MzVvvCdDkLUOPXYXvfYchJ7uRlHygCnxzq5jBCHmGrtq6A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: vaultwarden-admin-secret
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: vaultwarden-smtp-secret
spec:
  encryptedData:
    smtp-password: AgCduq8Xmqe0CjYmMzOQaW8GYd3hnvz0EtRyHFQQxTeVw9Fg9hpUnisUzcwWizN4yLp3DEIQT8G1L2ZFQMBBFWFksIY2DRMy4XI9IsiLYScfmfqUTz5H0bLPA2IB536HmqlWIMYzhzi04a69rL7saUXvP9n8mj6CTnXwsng9VE5cceqDP4U66Qluj7SyGY0VY11rNGrm9sP9h6+ED/NlMF/rx77OIZ68HMoGbCfAonmeWSpmCJgPjAZX7g/uUHoAdIl2xFDPHh4X/8nEdQ8kb9tsI1yHrZzKLgJYeOp6y0/gLRtnYUbzEbuBc4XCyg61WTn5Z73ETcFmqdRyYqyRghDXKBaWsCtRcSzu8VeeIsJjTL/9suDlVLgnuNDCwe3vYvdktxh71M+lvnAYamlGjr2YmJJFOBDyTXF6uppzcZ8z+ScfSwt4KGdK53Owdum3NwsL7fe+Hj3GnMOKqUToOH7ZxfatZLpwhfIdGxIJViCxh+neo/7KumQLK9BUmYgfvnqiNHt5M3BA+LnbaBr3UX1g1Z21dzpeUkDHgZ0NS6+T6AVBwsyjUA+j8w4Jd3FhkE86cSf21+QxAEN9woOWrt1rNGZ6//8brHQbDspZHNFAj/cvwEU+9SS9nG78kO95WPVAfaYtaXn0S2qZHtsRPIkX88mkIlXQyckOnhRcWO/Yylcu6sikpOFS/F+j8F55JEQuQqmIjy9iNfMOPuaUtq+N
    smtp-username: AgBwTpCAWs6J9eAYTINNwgd9p3VPr8zb1ZaDqIv4kLoDY4dEzE5qmbcizcO1RWsgpNRyQ0tz7WOtaUdw7v68J2eBE5Fddg1Yy/wm6iS6xuYv0PejqxpuHI+QNPY6upFe8aXxs29GxpQM+qjUjdrDmStlS1MCi+GWYk9eELNhhqzfJT+BQSaYZEJq1uAlXTi1sEKlpiUgUSTepQVOeshH/YvajVkLjYSL90pVyVha0+mTiXml6DGlMNO6rBD29vclnWMyZJ9OhmoqE+vU2oBhEcQ4cgL+c6Hlx1I4jq8Ilagzehgk51JCm/npHnf1p96XlRcSW2HO3MZsCqOIfgIY64snDv0KLTbA0T2vZ37Q1VoFeH9NLbyqbDkBzJbhytJvRDnaRkPNwPsA3n0Djg40FfP2mIN0kDYA4kUFhOF4yOP/bcrOWewpDePNoI4ndkPjTqeY89u2KkZdxqHf0MUnVVBQNjNge9koVERC7PpquMl1e2DBxcKi7tBdx0o8pggcZtLZ/a6oNBFrW7bF/vR7LcrDPM+UZP/gsLjOvnHmYXg+9gs39mb6ABtB1RKp1HVmvHfNjo++RZ9QbyE/DrAvW9pxY2YVGXU2yTFyLNtygYCO553/u6V5NoNM8sn/bBzKNLgJ/xKXtXBxA+CSO3n1ZVIbzeZOzDJXwtWQojxZ643gEDpec4oskfNhA7TRw2UQeTOSMvb6DWBQCeIeHzJmk+c=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: vaultwarden-smtp-secret
