---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: palmr-secret
spec:
  encryptedData:
    ENCRYPTION_KEY: AgCkrYEH/2TdWLw09hP2Jmi1w8vFD6C24fvtV/lNDPKvsk+UgqWly+JWG0Iovzye5xYUtDwbIlvwM+1PJGHCTbQY0xXbI6d4cguMM4LrE50xbeDdX04aLR72vu/I/4Cou62HDW2sYbgRyW9d6ELY/SpnVZAhdhO3yG4TAShVpqP06BxAZ6dkVBSmvQI+md7Z0g1f8+OuVzrBcrnq25AgXV9wpFEOVBI/SyelVuuG0SJK0kZfyamvgJWjibFurPOxrgDUyTu8CJOsaogJ/uzBj4891fLQK+mYRassWSfLAtnJR4P6zPQVbHuJoi+QIEvYiBoaPuHLQLGDmus/92CmiKPt4U9CVvvB5KuoWOZOxWuyRwODhzch9b90/QMlmWIHzkNXhnP2b496H3dFqzuXb08diL9IZRVWYQchPF2JPMVqNAncC99qn/tq84uxrqgBzkVRL7ZJcfoclwIC15WCzv79CaLxAXKyJsIlmA3kKexwp748kGxgYi8oLsxSNWniZZYoR821c5zVFvYDa58Qh3oKOfPRL/CyzyDj0b52tzxGzjjcR+rWdohi1TW/2ASxYxF2AE6QFZsMtpG+z7tuyeGw4bYJX4lu9PVWJX8hoPYrErgRRtfdLm/8LBLaFNX5fDRMZtFcxZRzHJzUaVoNs5CWpSVYHLjWSH/i3hUDJadp5jLvGTNca7PBGZWC78zdJGtPuNM7tCHiobHpqH6o3wAGxNLuydwi41ozIEcAOEl8Oz+Qr5JkvKYo5qrj4821L6itk+pUMpW510NhLzV8HvQi
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: palmr-secret
