nextcloud:
  host: cloud.nasus.dev

persistence:
  enabled: true
  size: 30Gi

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: nextcloud-postgres-rw
  database: nextcloud
  existingSecret:
    enabled: true
    secretName: pg-nextcloud
    usernameKey: username
    passwordKey: password

cronjob:
  enabled: true

resources:
  requests:
    cpu: 10m
    memory: 250Mi

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "32k"
  tls:
    - secretName: nextcloud-tls
      hosts:
        - cloud.nasus.dev
