---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: hermes-secret
spec:
  encryptedData:
    DISCORD_BOT_TOKEN: AgCd0GQ7R4Zg7ryghZCF41g7nFCYLdKuTKOp8pqqrN763fj25nxk24rm+aS/9O7+eMtE1kEjY4BOWmlsRnHrygxdSQXHj09AWS62e30agr/FBDaPtrcGLvfBwszsKhecc0pcjGTQ1VlbVDLRsu02TF3r61gnUZnesybpIxTyhl0QOnAI8akyACBpcl++vMtJCr4r4bSF73nWPTF6nYgUD9DYjMLhE9UQFM770lp50+FA7k7IDSZ0hYm2jlki5Crr8SN/Id5nVfmnUr64l7fkdL6rIug1u0pZFDElFpkU40ql62kdRTMgluM2oR6g0PUeAkiHivg64RKHD3iYrN1nz05cSVbunoMJjUGdFxF4eYp9Hyb0lhDoujir9zRP/aqWsHzb8/SNil8T6/8OftafA3cO2vW8spepRX9I39l6qKseaWNo5j9R/aGPWTwduQ6+EsTrQEwIaRr4kpRVaR0t5a48/qJqb27vG3BLwBrq+cUPhYrKUdDZaL+tP01mtL8koZpOmYGXe0TVPLC95yGT34soUxLMLkZkY00aW3JPZvhnIc7WgtHeXHQHPaXx8n5nv15Xs+Tbq8n8trrBu/GE+v5QOhoTEXSXfCsARvs17h8yndGeCpBXyF8bOvbJd/7djFqZFhP6Ybjwh//vZi3XF3JbHUud/0/fj8AzYmVGI1VgMHqsaKwzD6Botg3AW8RkbrjrxpwtMFP8PYn2yEzQ5f41YScairVra+d3dV4YXdDoKnwLejWOFkZbWh6GbZMpSfwfU9kfeG8oVX0ns9Mtn3kjL+okgWH30Ds=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: hermes-secret
    type: Opaque
