apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: rybbit-postgres
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  resources:
    requests:
      cpu: 20m
      memory: 125Mi
  bootstrap:
    initdb:
      database: rybbit
      owner: rybbit
      secret:
        name: pg-rybbit
  monitoring:
    enablePodMonitor: true
