---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: clickhouse-secret
spec:
  encryptedData:
    CLICKHOUSE_DB: AgCfUItFnVUezOaVElvJXLUU8RkPERwoWDV2hBkOKVLCaPO1F9sxALZ1Oa50nVZn0pcwME5Jk8i2QDMMQ4wkL41rtc/v9AvYRNauzFe+1B40l0DZYBBbtCEAnypgrN1WbekiGVOndGC+rFfQW88mb/7841yOr1j4WDrm1sOrR82Zily+QdEKZgtoGS0Mnmua13inMu7d2Ry+bfMwsOCUQ54bWerYteXV0UI+/bD23zEfVImCdan9UShOwb190vCCz7XMr+ZpOQAL/j8aoHcEhRpXQqseu9pDu8zeyY+papmLUoW/i9o4maTmhlun0nlBxQoPpMHMOhOMsrSCuvLNfOfSVCZfGIwPjMhlhqvRnlFOH6wHYLVd+d4pbJZWXAZU4qe+8x/bUJ99MLJJuTXNjyofaiNYvkgwRliXBYcwZidDv0m2en9Ojpp/wUjcLmkRO+GOvdhajunPGc9NaFPMacT7eC1YveqBVkIazrycwk3XncAXbIO6Ujjs+uOQapyWkiB41APte2+2bIDN+ZhQJmreGBmy0RdO+6ZrUv4AG4/2IXEE/gqmZ7Yhs7JsxMrYMElseOnuxBMMzPF3x+Pl9bQznZN5RRstX8tS9Xg2cuYNMwppzICAvvwxTPvioxh/eMa+Pk5+DqadVmLRFP46xht5+ihjN26fy3GvOGOwrSPIGIWdgnKTDNN4XmWU+9k2CaxHWxipAjjX4mk=
    CLICKHOUSE_PASSWORD: AgAjuQSclcWd8zlPCzS1mqV+EB0Yx2TMQBc38rCQQQWTxaHhuwFUoIvH9k5d8mOwBOiuil28bd94ubGMv4uKN0Slu+OVT3Xr91j01WH0vRh3ZRK3MZpS9E3aEAd7O0Yri5cpCccx9WyvmtJopSqCHtDBnwJsek53HfVDA/bZDf3hYIuHHTT53uoSxiW25eaHt9aEDB8ANgAm5tdtj/b3coaQC+/dBX0yzoCxn7EYJcOmh61OUUgLc1N3/ZgupTq+DJ+aXJo48yYqwvKBZSYjfuMEov0/bfBVQrtVQaQ1exDxPV2p/DXiI0eEzbs/BzXCYyHDf4wn+DdREpsZlI1xSwp3BhFakVM5XOldm+M424Rb5NWmrkMh2ru/GVZapPhTW0vNjlNYk2FePV5AWMSUFuMdCicjvJ8BnvO/Pbn7hvqJLbpK7Z0HFBceaS2W58grdgNVrLDd376gEWgH5VlxXdkPnhOY3R1OKfBpZx1tyQlUOPa3HKSJxTfzasCzYyBObMY79i+hNX4YAkCd8nztVyJU4Y42AS57dYCcgj+AAyXlqww4Xg4IPMWSGDxNjJ+B+xcvkOMCF8jcTOoo+im7qbv4ZTEvwkOVFDN8EgoN9si2AST/fOhxIBPdZFN7r9UX2DMN0/5ITuLq2OXgTcVTlGGSTzRdhivMOhvIWVcFvopFMPynQ+/vTyyk68DkeYx8btSiT+DTN/eqBwk6/I1gndoy
    CLICKHOUSE_USER: AgA/X5sEmX2/I0Eg8nju4qVrG5Ig9PDkvkaG5u2TTok20RWZpbTcovPM6WD4jDhSnJJ+yUteF/PwCV5vUzwvqIOs0y90lys0uZ5K2DXDQRF9tOlPUpsIqi4URIPwn2jPH746E491QOhZeZRl0d6qV3WfiHOfSZd7idpEADOHkSENrUuDesAtIui1D58YMthgX5LRUOe7ITi5K4VSDly55Kr1GPAyMaEp58zxGP56VbUPILG4DA0Qr70tqB2x4TGEMiVswMuH0QMNG1/YLdef+eTgC+BEPzozl04IyVhPaasrQLFZsYKP5XQ5eiZCyL2+CznwfT9rl2Q7mud3tUWFJj8uaAdKcYjx4U8WXQnJDSyADd7IMd/TaQT9VgvMJQl3NXsradIglstHBXvgufLHl3KI/zFRs3DupkbnKggFyZAZKkq1vH4PQkmJ8UGnZikgMNBM4XYfFiP625x7Lm6NJX2WHCY0SC6FREdzhlaiLn7vahfxLM+fhWoht+fN1ucQ2Z1BOHmIBEHJZFIXuD4rnUcmPKureaBn0kntrlqzKDttUGZVLoSrbi7wd0KAiVzi0Ij7X8nBQEdU/1lPC2O3zL3sjKGG5jt8ya0+2II5+GPEh4MC3R/uAvmlfXDZ2dS3eyEUAJHUta3pUjUbAdke130ZK8OF2XtNAIaVOffzYCELYuzHm1YxhV7oSSvL17MzJqp/Kht3QzKY
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: clickhouse-secret
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: better-auth-secret
spec:
  encryptedData:
    BETTER_AUTH_SECRET: AgAeVvcQg2Q2zH7U8M5dOY8XdNuvc5XLnrvYLMsqv0KoRvDCAwj8xdeFD85Xu4JS7uTDJ/kndvC4VuchJykSPPCd+9w/ewnvwxdErv7Kq1KDr7Jl4xp6knAwOF5FAvjyG4ny977PggegbAA6+IHm+AAWePzHlGjuAZXUB7lawfzDncD6pPwGlLuFt5dfZbpy5V/qkK0+GaLFLwmLH1rFiV3daMYu5FFNmZ5Mki5jlPereMPxTCmQ534GLW5gYxdYurz+hItJODvKsXWDmT3y2iLVkkVn1OSiCo/uCxlI62kMaHoVhDorBOfCr4rm36cZNnE0B28Kan/I6Ifc/1Y84Oiaq5HxVKEzcj2dSE5Gn1HqJBmViITbvvWlT3TsEUEZA50KUjsSPlgidJ0rTYSl3Mds+hjki57nnOlVd2Fub2TgK11TGwk1BT/nEZzBXLLkd+3kv1tNsg4F6XNI1Ht/YmlkCyLiQUjOsJxpizTzfCYNGZTBnFNsXnffGBATB42Z+znDV9fiq899lTFYfRuznZ8zLeLkFnpV07zgVNyTurcIDrZOmmujmjfu6NtdAjXO0fBxrsbQbK2yetouoe4Wg+oiCR4G393LoqTwaAyZsEe3dtck8sMX7WoI+yJj6ASJ7aRM8He1IjsZh11GwxfdQLiRALdyKWRwoKwJDp74Dxkn1YNPjo/d/IGJhHmPAHS0Rx0734ftHREQpaP3R7Dzm+LfSypdfh46IqpVZiJh4UCkxRvjsceXoZK9rlnSLKJxHSio/FhNZXl3ZSL/lCPX38nu
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: better-auth-secret
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pg-rybbit
spec:
  encryptedData:
    password: AgCYUJ0ok7HkwM+aQ5JHkWdsRIYaDuDUv/FXIUmmiQRrUQNr/xkrt52o2Hc4febgSDrxKABiu8kO+zhvzOPl2UsWVKT0P4BROpc8jYZHC+zP+ifiWkCDcrYhhGm/oBLw95Ru3GoGdN3SaLf3q/bBrLIBcB38FGPOXt+XfggumDof3i/ysulyOsNX5XN5NjVejb/SBMed8q1nBPX9FHIOHK56iBGjg32rk3pzfqdUkgC4ssoJ4ir3Xhc5bszcJconSgTfr2ok7H2q1Ih2vrmutD+UrkbPlhymXpllArvhS1/Ep9cVw1yFvHLyC8OikclV/HLhLNM2LE0WwFT5Rw/Zrog7oisC2H5icoOUhyg5eoKPjCFFc1sPbjtxD/qUyR9QnHWismRjw+168x3OjgB7h69KHOv7Fz6gkW2oubVMmylWjeoFrGX6ai1Ugk2IwkzCkAF9JB+stDnQO0I2GBaZzrr6kUhCTPEMSXVBPotywF+MH9ArflGgKWfetBdgkyVGq2AJKhJnn3rujDFmap6QeAcDBzU1nV/FHYZgmHasdI8pp7YDBnBl/rxQtZ/h1BDSzOXjrr7fkcyHAlB9e3zLSpb+aBXZiw7An8XPu1OL38mpDKtB0I14vsh0i8GEfDsj9nJxWIER6aW2d+NyTGqw5HZm0MVAsG5+NdKTWAl56ohP7BrK8K4BZdw4DC3xBFlB8sdKt3zVCQaCldL+Y0Y=
    username: AgB1KWwZ1SGcOHiDPNa1OvIyYK3PCWgO6quPA6GcxNPEtZoLWne5HSlWojXB7vAHmkRs/J2tejHQ7eu77k0t7dyO6r/Cghs/JJa47wrLdjdMbjA0YtLw8j/8qVbyK9JVTytUgMtBNQ1XGhmGNi7cqWJpIFImTEADo12nXRyMSMFjyY5PFr6SzKMvozWNg0sMV9TV5Rhrp0KKSJvCnEydjpry4fMD61mFeYKweZb7tkhP8KWmlQ8BbisCTlKMK6sGjfFTpjIO/n9foSeyHRxQ091Ch1rG/wg7BCoKn5bjkk4Tu0O/X2ac1+cfBYM+YhKpdDYHr9N8VNprKxg99E2HRWSMeplqxSulYN5spnQRjtm1lNhdbdRfvitv5XKeVtR31xl9OZiW9pPLEStKWoC69J2vOZ1Twobn+iCnFuKbPhtWbO97OiyNUSs+iQlMmZCM2JSSqnImw16bFBjWpNA4HOcmIfIqPZWii1AviYzAPSO3nwxin+O986HVGgrEtF5XEgH1jV/IexQOf0wP1zjKGXSXqMyOEjEoLkwb4E/ISecHDBOjqgFcBFg3HVJGDLxUQiYvVhY5HSnPRvUnKxvDwDBELXn2lRd0xlAxjV2lbZbx31Z5WLfocU6StnlqJ18k/PlNwFUuAO841f0p+fpi8K+NSsVhOARIDorsOdMlM6NrnmnsPbYh1QMRTb3TrlkPeCF7zWFflTo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pg-rybbit
    type: kubernetes.io/basic-auth
