---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: meetup-secret
spec:
  encryptedData:
    DiscordToken: AgB852A4FdkjZWI6el6+H1VezFYBnjcdlCw4sOwex05x4OwqFjjMbPgGKM78DaPxd51i66GK96pI/Tf3XLfC/0iZzHVPgkxoFIy8qzosRm/fkFGK7zvnRTbPCsMcaKiq1Hrvz9BsRMMO5HDU5gQZNPKkRgDIikB4ra23fv34I4beYFn7utuZfuAeAqJG9y+0FQCT2EB75WBcuFIwvjnqwNRzJ9gmWlPmNwwFMPw3pwPPRLz51/yyn3f/xFmIQ3GgzhAE2GL6/f2Ze7xDRqhnnp6frjE9+/fsei1YwOCr4OggjMp4YGFTy9PiU2ilFt6OMBIVq5Eesxmeuhnt3c/KWVtAObLmx4BR53Dn9jRwR3c1RAxEzCdQoOyksv1cFxSzAcC/wMmUuXVLScGskSVUpWswZ3bhfLKvEsAT4baPqJQxV36fWsLLIojJiDGhHAc9YnyHNIGxg6gMWk4it+NGUWijnpW84iudhjvDe96+AFLJU9/BZ2hrnLW8OJDSI0D8CPb/ELWdwrG438vjg3AEMWi2/hqY6fNyejC3ACumuTyQdnj3nfnTAhxAT4oPV4hJ877IfSSG55bf/nu1Eh21QWFZ0RA1rG2P55BjGpRgwSSN6nIvsLMmVsjQD3Rzbpiu4eZSLQ7zOo2fS5zPBei/qfgCg6nxCh+KGANXxZ3jjLel5q4fqoa7CB4fCMa8i5uW1/IGMEQc1xRWc9OaPD5BMdMaPgviTJ12yBeiVyDdZAG1N0nc3CH+Ds86RUlXyI+rsmWVH7R4K6mFxV23IxE0xOv45q8RuPyLFdQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: meetup-secret
