image:
  repository: immich-app/immich-server
  tag: v1.136.0
  registry: ghcr.io

immich:
  persistence:
    library:
      existingClaim: immich-library-pvc

server:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: immich.nasus.dev
          paths:
            - path: "/"
      tls:
        - hosts:
            - immich.nasus.dev
          secretName: immich-tls
  resources:
    requests:
      memory: 500Mi

redis:
  enabled: true
  master:
    kind: Deployment
    persistence:
      enabled: false
    resources:
      requests:
        memory: 50Mi

machine-learning:
  resources:
    requests:
      memory: 250Mi

env:
  DB_HOSTNAME: immich-db
  DB_USERNAME:
    secretKeyRef:
      name: immich-db-secret
      key: DB_USERNAME
  DB_DATABASE_NAME:
    secretKeyRef:
      name: immich-db-secret
      key: DB_DATABASE_NAME
  DB_PASSWORD:
    secretKeyRef:
      name: immich-db-secret
      key: DB_PASSWORD
