image:
  repository: immich-app/immich-server
  tag: v1.139.3
  registry: ghcr.io

immich:
  persistence:
    library:
      existingClaim: immich-library-pvc

server:
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: immich.nasus.dev
          paths:
            - path: "/"
      tls:
        - hosts:
            - immich.nasus.dev
          secretName: immich-tls
  resources:
    requests:
      cpu: 25m
      memory: 500Mi

redis:
  enabled: true
  master:
    kind: Deployment
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 25m
        memory: 25Mi

machine-learning:
  resources:
    requests:
      cpu: 10m
      memory: 250Mi
    limits:
      cpu: 500m

env:
  DB_HOSTNAME: immich-postgres-rw
  DB_DATABASE_NAME: immich
  DB_USERNAME:
    secretKeyRef:
      name: pg-immich
      key: username
  DB_PASSWORD:
    secretKeyRef:
      name: pg-immich
      key: password
