---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: qrnroll-secret
spec:
  encryptedData:
    WEBHOOK_URLS: AgAzEtk+ht8UnQ5SNfcZmNUWWrcQ4W5s7xDY7LMFhfoaB0EZgiB893x1kXMWxMkngL1b4O/eYOkiDhtXtM0TfeG8TjslmuNfwit6MS5+h6nQQeIKShGGz8IcDsLXV2huVktNpmRVSlsJRe7V8l9vrT2m/6UQ2o1A6PwcHbu0SvYXKO0ddKKBmoV58rjV5FdXwStIpmJPO1BX1wE55a1jdZ/SSouy893fSEFUGzH1KJ0i+q2JerZ85auTNAsPKJHHwxYlfe6coyfbAWi/u1Gpbm64smlZW9QR9d8P+gICjVVUxMl8zUchZ3nqsZXPCCbRd7gQ8dRjac2J6/ti0mIGkCObdRpUrKb0toFi1r0X16P4934SlLlTjJHKjFI3MnJhwLe68+uL0NxLxhMuB+pN3i38wcl0i5E//ENMs7/Dg+11b8dLE8jdtIFMV+vaWY5T9RCmRHkZ97cvjHHW+SmfYzM29b/f1BjGBsnJWSU4IFkL6bYxvwmFGejpzsTwPmV2JKtOHY6uIXzSgLSjhtJ0ubQcgwliKQPrv3X57+mgjvPlRZeNAq01ZxVsN6TSjHcr6s0TJLDGPFero2zSVhxVXnJznx9Zt4yWYZKFtbGPrak5uGWGJZPc+52nWJAuorJGSzrMkirRR6z7J9FlkjLITISSlyluzUhXpFcvoHTpjGnVs8kAOhbrtr84HdvFnPsJ8rJ6IQYk2jjsEqCj4dcgurqqdbZakl9weN1jYcFpiaqmGUuXLfYS7XI6rmmfXv3ecNL+7ebbH83j9rgcnBV4Dk2rzc7mvHnUPwwiPs/SNdpL0L/e4TUnoLrenuH4zrQWSgYKFYvsoomTyH2DrXnmaCzquhWjI5ec4E3l
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: qrnroll-secret
