---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: qrnroll-secret
spec:
  encryptedData:
    WEBHOOK_URLS: AgDHUvAdLtHUD3VpsBB7Plc8WiGGdggS/6sQ4kIeCKa1AjlAbf4dYCxGPfveQ6dI95appyMOvzTVI06El/J8PKc/w8V1VuAAAvl0Ou9J2VFnDIvhn247z40qt+IA679AJv1i9V3XJ2vkhfRDTztxWlLq3sKxxrfDJ8PAddba7C6xTPrexiYiqBNuaKr83zAWdhSlb8xUP/8C70luakPufrKcZPVClM+FrnYKn0iN1qC7Zd6Y6mzYtrlMGD9nMG0XM8vNF/sUwdOBKVW/84+VElszljTxnq0Np+hdiI+w1k/6lglkMCEORp8W4FWx3y3J5VCSfADWmWjqWTH8jRnSuUz9jWNJlQ49O9SmFPsdL3DLfZuGbUpJ35O0VidaMDQEpN/Krhq3VQ3p4Fu7ocv3+K7kiaW0KDqTre4m16h06aUaQBlNkaQMNdkdU3Y1gMTl4r4w5AVJnlIXqUy62TzbI+b46JAQXdrAZh4NW+7fBYqtsYtGHKXwT+MsJ+ZYLIxPKdy0estQwvut8kxJmmviKtFSeOwSCMj5EN4B3neoFG2gPiCk/c5XXbYhI78g598DueoLtdSj31V+UXSf6pKMY9gTFxFtAGkRr0XABsHbLW6vfBd7q1BPyiaQjjCw0/kZ3bZgGyKVC4KSBmT5fAIdTPMOjkop9rGshhHyun023iQtHMKRc1uBe6As8bUebHUZfogH5SL1Ep+m5E2vp7m0AwzWxkaVlDJ1V1juCuCq1PSWiFViuCQzSfMDfunkIPmo6x4OUEr5uqdbYGbJMMNcVIgaLqh/lo5i88MupNmqQvG/58idG72OTf2DKz1vmTbnGIDF1iqnuCKugtdpIccLONAqGNldln0+Ui2R
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: qrnroll-secret
