apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: change-detection
  template:
    metadata:
      labels:
        app: change-detection
    spec:
      containers:
        - name: change-detection
          image: ghcr.io/dgtlmoon/changedetection.io
          env:
            - name: TZ
              value: "Europe/Warsaw"
            - name: PLAYWRIGHT_DRIVER_URL
              value: ws://browser-sockpuppet-chrome:3000
            - name: BASE_URL
              value: "http://changedetection.nasus.dev"
          ports:
            - name: http
              containerPort: 5000
          resources:
            requests:
              memory: "200Mi"
              cpu: "10m"
            limits:
              memory: "200Mi"
          volumeMounts:
            - name: change-detection-data
              mountPath: /datastore
      volumes:
        - name: change-detection-data
          persistentVolumeClaim:
            claimName: change-detection-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser-sockpuppet-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browser-sockpuppet-chrome
  template:
    metadata:
      labels:
        app: browser-sockpuppet-chrome
    spec:
      containers:
        - name: browser-sockpuppet-chrome
          image: dgtlmoon/sockpuppetbrowser:latest
          ports:
            - name: playwright
              containerPort: 3000
          env:
            - name: SCREEN_WIDTH
              value: "1920"
            - name: SCREEN_HEIGHT
              value: "1024"
            - name: SCREEN_DEPTH
              value: "16"
            - name: MAX_CONCURRENT_CHROME_PROCESSES
              value: "10"
          resources:
            requests:
              memory: "500Mi"
              cpu: "40m"
            limits:
              memory: "500Mi"
