apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: change-detection
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: changedetection.nasus.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: change-detection
                port:
                  name: http
  tls:
    - hosts:
        - changedetection.nasus.dev
      secretName: change-detection-tls
