apiVersion: v1
kind: Service
metadata:
  name: change-detection
spec:
  selector:
    app: change-detection
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: browser-sockpuppet-chrome
spec:
  selector:
    app: browser-sockpuppet-chrome
  ports:
    - name: playwright
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
