---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: janr-secret
spec:
  encryptedData:
    TOKEN: AgBjfwmYmR0ctdMs2ySKe50Nc0VtySdVEZDQ/0gWHIHtnXmJ0pXA+l/DchoVUdSCI4bfJTomGgamuXE+B+5O1cgBiZ9GnyA0ngLGdo/SvgsZXgHK2d0+HI6c7QsZAcK6MwEeKlLLGRHKFVHRSxnSKTW5Qd+caLqt87sVjJVZghLQu2ChFg8Ypn4jLnHHSTcY/wayz2enf8ivSIVjIGxxL9nWyO8L8KekNDJ5wLx66pktsTGbaDUEFvo+1R6mqebUWmbfuGrR0UHsaiXWN8RYejScgtz2QDgpX9pUmm5KqJ3veZ6IYAMH7iBW60zhBeZ+VKvhNmWTe3M9YH7L1SFqnEYBuFb3+u7sEzUwodxm3VOPyOyvyf8M+eR1OKQG+Q8i+PSGq/CgpYXCg9YonWL7wplx3Fx7pVJ1lc6bi9ygfcAHz/dIeGe6Oge0sijQ3sg/+F1HjochjTpy5tnvAljjwC4VTvr4BDyoTngumHDV8/IcbBNvJJ9+lJyJxWwzQTX4sQEYHGfyqnLspoXAWQ+CUntb3/prrHfyi0lp8mQ27vdO3VkAF3HS6WZZiQwJqYFolcI1DEpPAOtc8WkaWD+aNwcd6vjjgptJzdzGcQJI/7RTYFnMi0iCmiBG+yqVBAUnEUr+6DuqS9HLAFqoI4xY32osiiWhAaXnusjKDYSvypiyHj90ckzC41OcMT4gJWMwdEpKyIyuOwXuRsw2BGCs39LnSLrhMBNTqbRvoGnmLNS+TSZOu8np9GgSRAGYTj5qX19hD8OARKHRzh6BtGycpLBvoPStxPyV8v8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: janr-secret
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: janr-registry-secret
spec:
  encryptedData:
    .dockerconfigjson: AgB0HKjlJZlcTLDzSqvnhCERbHaSXrEY7lr2OZykt1yQbLgq7Pd1RVdo03AG3IP1k78j9hGN7tbExobAlFUNX4qKX/yHMj7mZGZA0Balj2gu0gmWdlgnZafxQRdnBUCPk3G0dfxSZPTULIyw4ti/gpcmh85wkBYRVxRVwhUvRYa8ICJ/leH00KKQ0fG8tYGX7aRgMIcpUZib6WquIfWzF9aJjgd3Zp0CqDClnB/qi0Ro+yAvskZRQfVxyJae/ZaVYtUJ1MLDR1ceSipD3lkSeJu5xVLyWv5jLELbGOspuXYczysFYxu4jjhtQ5VoEmsHQzQFL8kbL31b7UdXHJfgm26EdCFFpIgcLVr+Uem/fgD3hO1qQIVzQ/NwP46Zprwk/AbAn+y3hj1NpIGK4B4OzgYaOy+92Ym4DxBVinx+aU/7WhiqhgZxlt71FmPAyj2YCP5MEu3UFhevrqk0PzFiSXAf5iRmpslRLuWVRBwKaujhARXLeMATHYRnimrIi1UClFqeurYLWvje8AYT7+4QRgqMJHU+1rkSrJjb9bcVLPqYd4gqyDWKOuwzul2iGzw1EuMpQjBXi4tJQZZqWgtByfz5NSBdb2kHdq/jbUn4fqUtGflNuZQk+oDNIFscdzUzOIVw+eb6RbJiHFTeA9IOAvQ3JrcURTj8Eq5PlmPwfQGxi9M6EgMGj1vWd0Gi5BI+qXbANLzhilOsjh9248joR0+xR5tpHHwefkTWZqJ/nDLaYYv/DytZTusw8QKHxgDH20j5CIxPqLJCRoLY0LF9YpOSaLqBxmVQxCNHiU0bsM+YXpdiMxaomLGHGirD9q6wlg6vvvNa2A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: janr-registry-secret
    type: kubernetes.io/dockerconfigjson
