---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: vodka-secret
spec:
  encryptedData:
    TOKEN: AgA0reht7mTufAo7UUBUNXcrAPl/d9jmil+n0kvvQ/mIdHGSKsnQRayLsEyGmr6LflzJNOJHnbcZ8pyKvEI6Fkl4j6k+Oxng02WMGANqwyTHv+1l/bvZVfAjRMwiIAuJi6eBq2WChqjpJMVAz5NXtMqx85v7kCmvU1CLn34n/31iU5ssLiOBzjV5cULQnXX+3zYGQbsGemY0OphB0j3if4hK9hEKc3YYvAz0uSL78Ig5czQCGfBiKRbgaRjLjTWQ4v+ZCSR1L2wzOhA4kdalRN8W650Nh3nNrh1Km4fDWVcBWpM8Z/wXRYhnk5LUwXF9VYPCr5FPMeJ6boFAWpnB/reUE1naAYYkuOlCrQ/2rJEaASf/jKNXLYQo7hgsZlIJyZrQF65jhwCyhPcW4We8IA7fkyvivCHTcVEm0bc8Pp/ASkAxGcy3UrSbdq8NDp8bjjj/UWG0BoH757ZRP62taOXt1JwKbIw7unrnm89eRJOVOBEUz0mQAktrbj+0qDhOisMfaHc2bCwWHWImBaNEcNyU5VuVfDPGGXAyh1KDJunq2GUTYDW0auS4ThbgDod9rz8QYdpfJQ6HmoQFx/lW6rEL81LqWfuP+0dgZ6/PQE5sQSceK2rV9yFLMdtDMBVBWUQ1U/As5sTWwRY63mQiDuWqFoQw2TCaf7T7pWZ305tOGZIYvZC9riPc/Nf2H/qMud6dgPZeXReSQa3WjLf0nEDPKJX9egYdF1pZOjPV0TJFagwfqRmms35I/7phLJ3tQ9e3Ae4ps7TR2wcCf+sT4CBiBJMVy12WNZA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: vodka-secret
