apiVersion: v1
kind: Service
metadata:
  name: maybe-finance-web
spec:
  selector:
    app: maybe-finance-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: maybe-finance-valkey
spec:
  selector:
    app: maybe-finance-valkey
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis
