---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres-secret
spec:
  encryptedData:
    postgres-password: AgCs6BbHRir/caNI+toj7pCLcj7pUNJjxjteLrwXskrFOHixeHFz4HVatq7NxBFjdIp5hp+Q26l10slKBnai/1MJyLe8uvFx7DSTpoB2T++ZiRd794kuGDZEk8zqyb/UI41bUY4OHB39kqj5xS1azyLpZmoDeisUQV+FLk8juCh/syPh8kTfc88YXXx3COv+StTYWcbPnkZ6Vv6drvLA8vmNM90clzuCBNZ+o8WZjL1566BKkYOqS2n0N7ieiQju6nsZ0STX30TgIKeuWMelRKLWBMTyc5TP+Ybz7rZ5+t3WfyOIDkCu54qWe9A65hi3PDWWRENldos0pvPM8I1GjtPA9thIyC7rpp1Mg/dsG1sCkHWUP7Yl/EHmex0kze5s6ErSUcpGCBuXVoljNC3z5psWTy2D2ecnIKc1sfAE9/ha7xk30v1+0VfcJlv2okV9zZqtqhmkBS47revq47MtaSlKDHccxOJkqoW7wpwgImjNhs06ENEXCkQ33gz4IaygyjaiNr10lGn/stYmmtq5Xoig0UKVW9PP62F9QAHsZVewOGPRqHhK5o5UiE+A318oaRSiNY3dUlLI9FGSl+TXAyJM5iA6FkmDQYrhP5M9fZNZ4NoClH5Vnb4P16/ctw/l6ApY0j/wXJ2xGQhoB+9xaJ+Hqk1QwaxYi8O+lrRI7iH9kimWlV+25BNn9fx0gxcQcKaQQmWbV+Ply0Izy9EFXPBn
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres-secret
