global:
  postgresql:
    auth:
      existingSecret: postgres-secret
      secretKeys:
        adminPasswordKey: postgres-password

primary:
  persistence:
    size: 10Gi
  resources:
    requests:
      memory: 200Mi
      cpu: 30m

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  resources:
    requests:
      memory: 25Mi
