global:
  postgresql:
    auth:
      existingSecret: postgres-secret
      secretKeys:
        adminPasswordKey: postgres-password

primary:
  persistence:
    size: 10Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
