apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgres
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  resources:
    requests:
      cpu: 20m
      memory: 125Mi
  bootstrap:
    initdb:
      import:
        type: monolith
        databases: ["nextcloud"]
        source:
          externalCluster: bitnami-pg
      database: nextcloud
      owner: nextcloud
      secret:
        name: pg-nextcloud
  externalClusters:
    - name: bitnami-pg
      connectionParameters:
        host: postgres-postgresql.postgres
        user: postgres
        dbname: postgres
      password:
        name: bitnami-pg-secret
        key: password
  monitoring:
    enablePodMonitor: true
