apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rybbit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: https://github.com/Nasus20202/cluster-argocd.git
    targetRevision: main
    path: apps/rybbit
  destination:
    name: in-cluster
    namespace: rybbit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
