---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: shlink-api-key
spec:
  encryptedData:
    apiKey: AgAi2+6AyGhZFwSjOTbpY3bWa7CnTIy0YK4GLGj8E4rW1yIaQ8a6UXAWcniACOp6ZwhygliLlPMyr3//XIss5tdWN1+ArluAnLw1KE+l/QR34+TlsU+3FD5tNYwEDj3kKAgYt7saLVMVUvbRAbUBUk4QsadVAqEnG5nKDPxGNkAwSS3IxTlXyxqaIQzaLY5L1xl9KOFsZ26ijb6ERN985Hxjo/cnyuILvYw86vWHImaQstQfp+vVGnUxUV3ZKLckOBpBdypn7S7m8Bt5vyzThJwESg+eqVMxN/pd4dlhLDNLrOu6cpEvmadksx2monCNANBEyqUxvw6XDExdhpA7BtS5luq6xzFUghsBMF0m0MWQ5uN13MQ69diZpJfAqbY0+uNk0vvirI2nzF+9pOyTJUrHKI0a6GQe2+cwEfKg2WJfKAZPc5Fl6yOqed/cA1SyaMZOFCaV23X8PGtVdQynI0ZR/kMCCBjxXqiRiPce82Yfur5+evf0AMmCFxGwEbjr8LmWGjrtbgp/+MHrEhzMc+Yq+GkBafDi4G3jSuxIz6WQrSJ0Z+uaKRKH/MST+jnB8Szjp52eoay+aDIkK6G/sxpuAAy44HY5HAjQLxDcN9VWEod833qUM/AxALKYnyYsuPAL2aZm4coherj0SFY/a3xypB4/epAIaGi3v3ZVtvEr/r/b6jBpP0k1qQn/MC5M2NquXJWFJlcgWZuI0AduFvTzmaMzeqLxTxRH8NumEjh3LVPfb0I=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: shlink-api-key
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pg-shlink
spec:
  encryptedData:
    password: AgB0AalXoCo6k7419IH9dz1Y7QWyAGVM5X7bA3Fllw9jUc8ooPLnJXHT1psMGwqeo8qJnIB7PpZYPmKwPnrVy1jiuT2JyQtZlPl/EZuVhKOcsGRrLcMF2yTScJMlA8xRJUuHstha+115M6hdwMY7f3ESu0am0tvbjHYqILx4PYQa3RVjIba/GPOhDs5vqvE0RUfFu68LAxlqpVYailEDa3M4xCxSkXFlp0UZ52qljfcOySZ6caxMmElG3G4mIugqpgHBICGa+ugC9jcHS1g/gazMLJRKJhEObqZw8c4iOlOyf+Zncv99JVYtgCcvePsv5kC6S5FTNR+AS7byuSE4GVWnuq6MeGU4D3aDQ+iBeoPV4uRAAKUfgOAO/EfZjgWSfJrkKe1w6nDUE9B0ae7f2h8G0uVMgCjuEDLf1LyspHL00qKj4fw793cY7MSjQ9GgD0RbgeYsC2gQg4pjZXwjYIym9nqsf4MUcIHH3ir52v6OPhKjtbEEXXkUaO0jLpFXGYsY5l+/FVoB7tnznwq4cd9xvQeCmq2JDsaHz8dLVvO+V6mqt8+JwH14s7FXy/rNud9R9q/xFv6a0BhwGUAT5MB8fC/bmv1dDHt0+6Zbj8buT4rbWcEvgKRlxUJRMopc1MJ7c2qK2zR26Fy+Kuvo41kE1ACkEZJrxD8nF6bCuA2pzd6UCURnSHwajN0yfR7jbg3XLnb7raSvoNWScZA=
    username: AgBHnnNl/vTFrNsukq5cRHn3Ix43t4EfjBGU5o9TH7Cww3WtOBt7fRrqT80GgJHdrvyh0Gl7e/8f7y1dWGZiuV4WgE5YfQTRMM6kwJ/Us52Znghb8ijmjg4ECQphvxG/9cr1eMVup0y3luegxrSqSiGnP+nV1jcWoMu1sfcQ4Pfgkcww2/9uWoNTAXFC4ej331buWuwMVJqhdWM7qR6QMiH6NWlfIdaDCrfFwJWUvMzs8yqlPVwDlAK8zGIP+EAClzc7kTFgiO7UdWyZZ2OqGJqFRgy5IrNd5qQgE/cBxhMSBz4z7RJwFUkbThYLDFF03f72CTB/IJ8rPyGtzMKt/7Y6DQmSRSYLJHMgEmju8Xn7Jbo/k+0V1IMbtcqn/gZ6nwoXh67EfrdmxvU35brljbrE3IZMbxkOEqp2L5Dca6D6ThPQWHZOMGS4B5srhKnE6HLuH+ebFNKsvppYKL73QUxApLj9ImhKjz8wtuHeSNywm5OTrwpLNLjSgF363B7X2L/XjVka26+zZ2FQvTKJ0p5N863grvImm9Rr6KKOI16E4SIK6vOYvGTF/gBqkOkkxXvF1MMdsv6LS6WYKYQUw86afFJZmMm8IfdXn1THAyuHBws4+LLeCeqG9JqiM9qaxhgueuyykcHdrER/B9OkCCry6zgBQZ6lpV1UAN6P4/6jzfjTMvK6i7Vu2oL29FPqiPuv6J7o0Vk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pg-shlink
    type: kubernetes.io/basic-auth
