---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: harbor-db-secret
spec:
  encryptedData:
    db-password: AgDcSaYW7KAYq6UsjUsOCOx/cdE+VeHRmSzacNmXOO4cSBIaItaxQ3IeeXjCNYMb8CEGnv5qpbrhcMie+5rvIsymlo4+Muau1cAYBlXnV2OPK/ZsE5AOsft3RK3tIaVCL/f8JPs2vmE+cLkWmcrV4gO/6HdX1kur31UxbnxdDdNq2UlX8f8hrDxsdBBrhD5n1RkPMEf40WdyqAXmUX4sNFNed67b+dsD/tJqfn6nt1glc2pzHaofA5RU4aCHpuE6+DvEo6qo8hZVRFwTx7El0omg35i2Zy2tmAue5DavHVt9wLXDYrRahdYvoIj3CzU2hLA1OC8RYk/qf7Ss1pkdPFtqP1WxaipMqNKLhZZj0PvC8jtyYasLF6j5v6pnopCxfjOEd1a2K22BNalX/ycWiSPsOZARe6jLsOC9yRh53tPyb6bP2FEdCpds+GvZM7e2U680UJ3V3d7+dG9F187L4Tc1lTnLv5+qW51EHajMFLrneIS3UF1PRA2F91+lWSJYrRwl/nt+sRpYHDctOQLLSrbhCpacN3iIimBOVwttNlkfwkgrRxzYG1XU6SXSMuY4zDMJBJ/4JzttdCulxHtyqFi3WcRoTs5b8Y0uiEFF4BaRLG4pYCa2K33YNi3nzG6rMKVtXi8setfn6g7FpPJi1G/a4MxGYpfMEBbnig1Al1pczHqNEeoPtf14Ix8/9vXA/R+FVvSe2JA6K9hQu8k=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: harbor-db-secret
    type: Opaque
