apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  resources:
    requests:
      cpu: 25m
      memory: 125Mi
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: pg-authentik
  monitoring:
    enablePodMonitor: true
