---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: authentik-secret-key
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgAccZOhKJf4Ykqs/BOg0Bl29KbJgpobSKmFReSoPtZ5OiJokVOvQ6J5xzSfCfWsf03rkzJyMOVUSqvR6UUhIFT04nF7vy2xj5sp4y1eYd0j3U/GRoqDs4RK8qCZ586HVDpcuVAdagBaygKt/ufkdop0BFMttvBZMudxAobr6wx9SnYPXVQ/+PkK9dHrBwtr05fjZueYIovGna65zz79UcIiNSleUentqmwPAsIoPe9frks4L74Rn2iwbGxF396rCWd3Dd8U0ZoU69BO79IiXhQ767r61TLBO7ELnVm/baXiFqu5IhqDoy3cl/7YDtl1peG6Tcn19ZfjSGpneKgtRfodJFxrQtKbYtOGG+0gSQp5tUZZx9O2OEOFP037QiZjwyyusKRbI4ygXp5vtzZEyhm1FWuGw14zcBNKAsUP3PzFOaymtFyKogjQaT19H2DoE2iUn2xT3OMPpw5f8bYBPcIggUnBPs6ccuAcIJrSw7mHKK/6SxOebmlCB8sQEVybTiqXQEUmB0tSy6pb6mM5ivzwM/1vVuNa+5kwthNAt+VBkw5QRj0KbHWPOeIL3wj8EBu7aX9mvjn7wrefgxVDNsj+NPUVO2mijanGDCYwNoEAy1EUloyHU5AcsKzGq4jZbLzEqwAdR0iv2N7+D7uqs1v3b3T4JV7GQo/DuBadewfn6Je6X4CgRqCvElrk52Qk3iroqWBn0pgyHgLSidhnYnbIklKG9bR5WqF/19jyhzedKFLDgq+nr+df62IWDnbsq6u2Je36tX8+poUnnp0cvf37
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: authentik-secret-key
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pg-authentik
spec:
  encryptedData:
    password: AgBP941G8cWm32Cvb+ZLCQn+RBKIAIJGMBUXr2xenpD2G1YUi9P1BhB02ikf1i1blkLnzSSAz7bDvElM/UL2OpGW6lk9hwRXkWZH8MuPZoKbEjQnRjK6BsxIbWeaAa+sTt3sksaXyyFQtNRZ6uLlgY7awjgRg72kmONpcRdsvzjIBTC4XfMhUxltWjvY7E9+nBxLKKE8abVq1e7njIKeGOGM6Clpq7fCFuc6od2IfixGLaia0qRLmsJYrtrLpSSZed+ycXlvZUheUEvgTl9giSFMUYG6yHxmWnHoo/yhq0ueV5q2Gq2rghXowvjPgL3uA7MVHdXGQUCASBemKolo3t5xQmsqN2OUWQE8XmkatoTHRdVa5WjdadubSLIsqNgY51L0MYgZ0GeTpLJlwUaDre2CZzORbRGhtJpfSy18zXMqUf2Ci+K2NkbBZ7tUNupdk3UO5J5+x8oMcKNDwkxKvVfyTmRtabTc5xZ55aG8fqJoVB6PDSMJtga5biqsleS73k6A9FojSF9jhTEYcpy/sxSkmu7dGxsVTqU1ygDzw4zh5YhdHPb56UWOCY2JcCYZQ8rAbJVxsTQ64vqRPdiCzQC/8+xmjC6LpCRpo2mBSQ8CEdA4/0qhZGsAboIyFeS3D2PxONvSMD6Y/gIw/w88LSJInUJ3YtTVIVTyecDYNgVAsE2qPofh5KyRkdLOfEpLlxjmq2HwBidUI4eJdwM=
    username: AgBZlFyLEhOhHLvRN0PxuIMaMw0QnIh1H7E6vlcs5lFbp57STaljy24w5jzIoocCR/x0BluYbQ7ffwMUSrp0lsPvvjBfBaH2luTi+VRA24hKSZajeczfkNaeZmMn5aB7hJLQ1gb2wHop3CWvgmq/JA3xEkngvgJdnIBN/zeHA0f0FalwZ991nguZO+p5hySF8TCvo1EAAFJflJHFmnWyTsZHS3W7/LcgLE6oMP6REV3M81JT/+MKOlqBW2N4jKROQ4LIOc0+9LGrM8qy8lHb8bNexWEpDL9Nh8iDICA8/pZ6AWRZ9GI98cJ9gy+jNFTpN0BWsWaoYvLYxYXKnuk5BKRa3L/mMlRWCSlFL0EzXwTp0JCC0urFmSh7jtDJTIdcdzjiucXqJHlHrDq43ylu6P7nvf1K3nQdVhL6MC3mS8mgl0jMNHTGGOMB8qs8W3BZMAVMf3d3a64JekM6oAF06Q1gD/gXWYZcP7922d0cB7LzIOpjvNZcKr53yzhO9VIAsX2pXYkFa+1d9vhlFlExpmZYjvx1ZBcldbKqgGUhzQkolC3H33LnJeEbkC8+tnAx45wwM2or/o1BY8IBrc0ogRQ87u80ZHeZSsEvtZEKU83m/pcEZs1TyvS1iLGFs7traXfDQvXQFQKZ5Bym9gW36314RmV4zLJFtmcu5UFvKWo9feHEr6RR5SKatqUEVA9HVlZrSqHtI09s7QA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pg-authentik
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: authentik-smtp-secret
spec:
  encryptedData:
    AUTHENTIK_EMAIL__PASSWORD: AgCtm09BH7XxyFPwZb35/2EcgJxu0rTYYNVBdzjMPbxh5UvnNL4/L+ADYhamwn6L0SKs6LkpLX1CjnlqFBEatSZyC2AuOrRnAPfNVckIJnoyISw+YqckxzfUq08SgFWe488h57ZaoEzYymtudKTGd/3JoOqw+NkRnC4B8WeVyo8c09va3JASrMRh3qUKcYFEkBQDF4mT88j6Wf8t4R4B0fK4CG/sxLhAGAJi6xU9o5hbC7RGrUnZkLRE3WQSroFMz0ie/eLKSvarvWKvbJWoTTwgKplzst5BH9FLqEJByqE2t0Wlyfvems9FGhfincqlwARq2Olgcbck1Whtg/VS05onNvyZgBQu3cCo61m1A+3kpOpNNuUIBP6V3NsP0JSMCeAs5myacXSGjPZyYw2sybYEaHQUijbDGsUhNC1b9bbHWZTA4dKO/W7zkB1CmEHqQnigoEKuCC9EVa75Q8azCFYGlpuRuG/NE75rOU+WUx7iyTjTQrNeU+3ZJoiLNAOgImX9xlE+9/6gcgvG9rRUMiNTr93KyIcJrTXPHC2rOUQy5ATZImcv/xeMMo7d5zSEyY8kqgUniNJOSWA2p/1rOXHEPob4H89/BqGoHy8w2N7HVZEtPUnMqEMYpnftpam4nXcn0wpZU9ZhWo4Mvpy6Xwq94i8B01zMADu5t1SFWj+dXF7OskHwv6DP8Xg1pUMhsMxJw56qQBypLH6zfrg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: authentik-smtp-secret
