apiVersion: apps/v1
kind: Deployment
metadata:
  name: paczka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paczka
  template:
    metadata:
      labels:
        app: paczka
    spec:
      containers:
        - name: paczka
          image: filebrowser/filebrowser
          args:
            [
              "-d",
              "/database/filebrowser.db",
              "--token-expiration-time",
              "720h",
            ]
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "150Mi"
              cpu: "10m"
            limits:
              memory: "150Mi"
          volumeMounts:
            - name: paczka
              mountPath: /srv
            - name: paczka
              mountPath: /database
      volumes:
        - name: paczka
          persistentVolumeClaim:
            claimName: paczka-pvc
