apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paczka
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  rules:
    - host: paczka.ftp.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paczka
                port:
                  name: http
  tls:
    - hosts:
        - paczka.ftp.sh
      secretName: paczka-tls
