apiVersion: apps/v1
kind: Deployment
metadata:
  name: logenz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logenz
  template:
    metadata:
      labels:
        app: logenz
    spec:
      containers:
        - name: logenz
          image: ghcr.io/nasus20202/logenz:1.37.0
          envFrom:
            - secretRef:
                name: logenz-secret
          resources:
            requests:
              memory: 50Mi
              cpu: 10m
            limits:
              memory: 100Mi
