---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: logenz-secret
spec:
  encryptedData:
    TOKEN: AgAnLm/I6dcUzdatg8l7VY989Cnoa24GoFT/lr0PpS5VFP0a1NViPNqwlNWCZMEAemCxt20gN/IBdlW3WcrWzlBU4HfGXzrmZRjpkxKjYJxyBobXoar/E9v853wurLxDa9Jv0l2jgBdGQNsZ7Sha2EvsSQbl0PVyCR0m5TqEpeilpiCVDlSsmWJMeisA5M5tvg6jcKrbltl/VGqQWcrJrGpmHVYH8EiPxLvDUds6qQ49EsU43RlXuuM66s7+0WbADEOzs+nUxVPSTHkkfNZlYG9+ClZ3Gmi/Ooygf/xFo5kSccCuTSyR/9vaoIoPviUMmKakxNdXTrA38CMOBXcjc3beobSwucKKHgVRjPB+aWqiCFGQncXhA6m9gHQPgmSiXGB602MJQ5EKzbzKvCzpvISrUCnb84idL9MyzWlx8S/9CZLuMG4G76rqcXM04+m9g5MSMr0DSzyqUhhFt2UbkRCC56SCKFuWIR5wcd+8PYpScCYtTjqiWnt1s3PRe1UjVT5+4riB6cXMIIuf1nz/Kvq1gYGHt3chbwtnx53neo8qPZq1+Y4+oPXB06lYzf3JtT2UomWtwtzlDMb5cc+mKAyENyCnW2muz/ncul7eR6XUQ9AVnK/iIwvssH+5hJxChcJH334/xi+pDn7ueo0NXS6eL9ZIzYx8LREBdUz4j3vBy0U5/wZZ0oOoti1WwijAkSxRdf/mH82TpnnHElZ30uXowTPk7otKYsOkcYv1sWA1mresU95Zlwj2/4EsEYyG2+ftkcgWKoyol1VwBAm0ysath55tCL0/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: logenz-secret
