---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pg-immich
spec:
  encryptedData:
    password: AgDTp5zEYwfWUgTUAFrZ6lRHfV7im+EOKz1UexlkFNFBYL2d5KsTPXminaNJmdkVepiHztU+OjIdSG15URC/yrHioOGMBVRxCZJPGSgOKJGc1ThjwFz/teHa+geVs9mEgtwzho5o3KEznE6cahRnHHy1Mk1LT5Pc41rwhFhEaroq5RhQTOueP1TPAGwWRv7qmJRZZnbae4fGp8CuiTuOxC/yvzbPYy6a8BEwo6uA8TYznEVehKKnPslCFuGb67NKf6nzoyGkeMpVemI5A8w0Lg2L8xjVsgNMrTWeNuS9WMKy3Bty21EdQrbcKD0iQ+l1uvSTbOjCkyh8GJ52IzyF3OwAxvLLn4jraquuSXVKuPoAxvBDQUEO3v8Oz+xVEsK4LTvyPzN6u0Ech5hjl/9S5Euv3PkhtrpTqAz5CDjeT9LmWrgZcYVrtGNh79T2fYtRb+/OFt64RsKzeLpj8EKe3VlBhnfC3CddFvXhyhAeXLEvKqRnPT/M+4yOGrCoai6xnqjmfsiFoVsifY6j0QPI0Dnxlv+JwOgYo/cKzKFiyTYI/LkbC5Law9wGz5ewupwT6JzZg6GGZRLzTMT7i5pe2blJQ8SltEiVmz3LC8oKQIisgpNHQhtxNdh7YiCIB24IV873k7lm4DRahZGMDI9DQ9vgrSntNyXIo35QxbS/8ETQQCZVzr3XQ6/esojXvyzog4XB4M63tKWhV9v5XvA=
    username: AgAxwrohZVcw11dUnbk8JOPXbmDjydphHQS7cuyojEqGLuiZisqs77dkoqc7fM8dTjWadfyDIJ3T+Mn9Ulhdh/uU5HcpW9HEUzmvI413ICORTXbinO4Rz3crCwqZrtoGO0f2/2DN65KSMl71c2vHRXBq4VOYb+q3wWJ3sZmT30xLX45rigsHCnrFoHW0D8bsq29QB+CcXP9IAt7384ovp4xYDHfBe6wzWPoz8s6IBBbf65o5gZnAnpyGfaFmHqTCT8G5jRrM3dw0pvbk5TuRvkWNNIz3CtIZz8z5DlzZwVLumzWt4iujO9g9qTBOoosTUjGSUSwb770ePMcSkv2rPO+L1+1ZlxRj4FUzXwhqrW1R4I8J7Ds2ekeJJOUDRBbHzL7X9lRqWkcdixNmoSLXuBPESDmlTRKKZg7xOowSIU2JYKIgseOaGJuWRujImZxso3vHY3FZBwNcfx44rGZBoQp87wOYjieZc2Q9fiutHw97dcoldYH5SrA2bf1UsuhEMe4NJmXgPgKDntNkFaS6WRJ7RS9amsF0jxOgFOHFoUiEckUasUJat78PMpPwaBoTWSMn8xt61jrMjB6sdJJvjWebqXCYtZFfo2nzClxpaS+mRhO023sHLLsUqFGmtcTQYfWKk9ROjTZ81T72rQ4vGS8RnEOXnpwDi8nPJSDMYpW2rT5Toe4EdXWurbrosOMWZcVivGKOeSk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pg-immich
    type: kubernetes.io/basic-auth
