apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-db
spec:
  replicas: 1
  serviceName: immich-db
  selector:
    matchLabels:
      app: immich-db
  template:
    metadata:
      labels:
        app: immich-db
    spec:
      containers:
        - name: immich-db
          image: ghcr.io/immich-app/postgres:16-vectorchord0.4.3-pgvectors0.2.0
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: DB_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: DB_USERNAME
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: DB_DATABASE_NAME
          resources:
            requests:
              memory: 250Mi
              cpu: 10m
            limits:
              memory: 500Mi
          volumeMounts:
            - name: immich-db-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: immich-db-data
      spec:
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 5Gi
