apiVersion: batch/v1
kind: Job
metadata:
  name: vchord-update
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: vchord-update
          image: ghcr.io/tensorchord/cloudnative-vectorchord:18.2-1.1.0
          command:
            - psql
            - -c
            - "ALTER EXTENSION vchord UPDATE;"
          env:
            - name: PGHOST
              value: immich-postgres-rw
            - name: PGDATABASE
              value: immich
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-superuser
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-superuser
                  key: password
