apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingvin-share
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  rules:
    - host: files.nasus.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pingvin-share
                port:
                  name: http
  tls:
    - hosts:
        - files.nasus.dev
      secretName: pingvin-share-tls
