apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-postgres
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  resources:
    requests:
      memory: 100Mi
  bootstrap:
    initdb:
      import:
        type: monolith
        databases: ["paperless"]
        source:
          externalCluster: bitnami-pg
      database: paperless
      owner: paperless
      secret:
        name: pg-paperless
  externalClusters:
    - name: bitnami-pg
      connectionParameters:
        host: postgres-postgresql.postgres
        user: postgres
        dbname: postgres
      password:
        name: bitnami-pg-secret
        key: password
  monitoring:
    enablePodMonitor: true
