---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: paperless-ngx-secret
spec:
  encryptedData:
    PAPERLESS_DBPASS: AgA0aWI4hfu/HatAaofjiymNLV1QMUoK2nEb08d4fVod+hCj7GZMOHt95umKnolyUoE7t8DRAQVBFr7BZ1F5DBT0uCuaA8gPjTCiGIEbizBlLcIDFDzaIuWaXVOoCpn+6Pmn1yGa/iiZK3nxhthEe6ck7PH7OUQepQeKi3sHJQgVOZgFH8So6eTsljblIOBwNyuBaSvuKZo2DO/KIHqLSLR4kAw7vzXxfeMwmVAOStTRcDL4TYivryMeB5n2SMHlVjv8XhhTf5H8heaix7wqvArLln31AwDE2sE9IoW1bXxk3gijWpKL88EmnZ+XOqbcYRaPi3uJ7u450F6ZAxOYAeMjp7S8QJOn3hYUI3C94O0Q5Fnd8wWz9IUsdF5K6TTlxSlp5lIm/8IT+9+tGQ6hxMnKUphR5EGffZQDfVGoEyFhqID74IpmjFeM0awjdAtkvwu3k7F0plaHeyLTLW1pN32JgWXma+g8DsWx7FjrgN4Tm5nfnIT+zU++VLd7o+J8MDnN+2tzj204BDvswH6g0hymSDHG0JmRjUQqgwgDMsJq4YRdNX5z/XCVHOM7pXKtGWqsotdOI2KzsJyXT9vAK3Wa7ETUE5UWUf8sUI8JPvtXZowkAPnumf5W6O2PRHFissl4/4fP8gsGNczZn3YVHuksOQs4gM+kWvdwogd2w8RJ7Uf5scgo2K/P4OaCa5e/JnmTgAtGgW+7Y+Qk1iP4y666
    PAPERLESS_SECRET_KEY: AgAumm+yWLeQW5whAO3bONyj7MqUCKSIQteGiOd8Xfsm/U51WKAafVnbYCdV/MYZodaNVswDjDn3xaHTJlFMcpaqcQ+cjjZoXD4ZyD7Ynm0wnRhMphVoJ+8NW6CQ13hJ/oJUlu3rtGlgWUopjRmstW8AvJfD3DaB4A32znzJIADg+uCA80wXBxxB2UMua76o9WDR2MAt4Fxmou0NEnlxZi7dBeWz2dXHGUQXij8oFKZsyFcElDJin/xvwAT/SaW0wV9JO3Qa/LL478DezvZVNyGRS3DBLedLxLq9ONQuWVKyFo5r6F/MItJXnsjsTXxCR5r5AzkQ5qz80Pa5rK2NnD9pBtUB+VpNrA8S++44epX7o3Bi1N6KlhLQxufqc1Waw167pjKW9eEuFma6lJpTyr8KwejcA+BoL/eYYwMokuDDJKT9pNmXjBJ1PFXh1kt1KZISQLwfrcoYN+kHB2fmwBbuSR4K/otNisu9OlhlN2/SHESj15XCLFalXr57jVshehj4/L0jxEOJ0TPTI7BdV/yByttFyK4M9BL324siLefE3M+ekkMaT1wCWt9/UJHSyQJqhtYMprKqbRUvCDLN/wZ6kaq3lVvJNAuTDgLWXpZj57S4FCpMiLPgHy4Aq4otBo7IKAiA1q+p8bWR+cf5ml3TvqLFdARs09UVBWKX6xkawjHCiOAjOsf8sB1qyKfKqlLl/MTzCzHbwZkCICauO6pcVgM24C3LLdNryTEOHVOLRdt9FFIlvk83ipCpnVTabqRtwwc5ecei3YUR3bgoeGfH
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: paperless-ngx-secret
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: paperless-ngx-oidc-config
spec:
  encryptedData:
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: AgAMkEb4c9derROM+kzJ9okpVka31SHasnY6yRrU7tpVCCbFq5EiqvSSZkGZezadDexciEHhJTcczCsz4HX9R9rtr51GXjWSjFAUf308wkItO1s1wpt9yf48PZqK9SywHoObChNP+H8mbpeTw8pl0zqPXrIoofkgFRK7UnNZ8E/wsNOQzIRH92+osTFdxp6Pa5+PH2hxZqhuSeNdrK0gTBfxm+hkHnpNlrBrvM36HlIpnt9lqqPDSHo8NRxurBWTAeOeRRC9eqaXiWTLVl9KfBn7KxY3QxntDsu6+Ik/YEKrRvJa+sk9e3EL6NUu5BKlq+EABlN4GRybZRjU2/0a7nuSD14jFHwmW0Zphkt7Ywxc4DWHDWkNNZ4R2m/bbo0PrDbmYB/tNrMs+FfvcsR5oZ0DdmmhX8qMWQObffj9cVQnBnNwIIR9Tcne5HCLznwQsAXEUtiuLLCNjhZaaXlyuS6EmLnGxk1IDWp8/ZV4ai0IZHDyA32MA0v2qKrabtRYIOp6bbm00+bzepbojIAMtmwpOpm9ZFXg/2687qCqkKhsgMQhoEjEKOzspzeyJfa9sjBHJGQDOpF/tvqQyM8BVO3GgI+HXgokKaKgDrO0qgSXmN39tlPZAInKIfejF1yc3D7UnwPITf5asoBPRcMxmErwDRB3fcjANKGckmvMp1C88mBGAMhaABm9NU5h+qyr/Z206lu7tqLb64xrv8lGY9oV6PjqRJ0ChM0dQN/nrVBSgJivewvkDbE5AbEip2DgNIv/jFr1g7kLMYnKD6ot3sRN3L72Ls3XsdDGZmevronWlZARbBdfKwY4M3+/08JKRvdG1yj9Yz3vhbbLnUZ5qsjUaLTbLnQwZDkxHrF0ozomRv1tHgakIxg8n+QovO6LY3F4tHdZ555FZiu65yJQuAVdrn+inVu0jWlyHyAJQZmbm79s1FLLnmHqC3/yoYOdWWDt9LmqUQstdeSZlyd23XZsNrypkLWkC8ae790au+yFBmGRiBVeeeZl4GQKqSJaFUzaT3+We5TZZws4PbgXtu+B8hdd0TIhyS6XsSvicxxajXBTkgA9n1pbC5VUEtOU3TOYlULLWuJfd6sRSQEpQk1WiWkUNQBPw87dwmXI+EEZGL5Ir+kdkXYqw2JH2lUKQ4v4AUlx1OpzdBxjryTfKZVgHPR1l4RRstpXMG4CpPbbKoi/S6DxZCZNVPXW8V4sYHYor3q3ybm3K3+GCksUZ2+wDcfEBeOSqw7rVSPG5AUwJe6VfUHS1ruCAj6Ejrb2cCcwOyABZrqZt+9fohvrQTW3lDJLrHBMYuGWh2Mmkm76XDF422j+5xF3PDxMsbnqao8Q3LYLCopV
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: paperless-ngx-oidc-config
