---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: paperless-ngx-secret
spec:
  encryptedData:
    PAPERLESS_SECRET_KEY: AgCZnc8D9vlSkFz9ZWqWXI3zQMxPO4CLJztAlSpDamW5xO8oXCfwi5lQ1FcJBjgN3Rrrxpu4pRbrvp8mi3ttTBf8Ze/feKZDCJW15Fa9JHr1ng6qPr/Ab7rHOIYKS1QWjIgnh56HpKKktZppY0T1kgy4l45CQLEN7CogJTL7OMVta62NAH8oKOAKe4Vzb8dDEimb+YGfR7LdlejDonUCBQpFH7frOj/biE/yhUYfc8OvrI/OFph+Q9v6A+zGa5Ie6oRlVNeVEk8Pk20qhho+Ehz0GuZBEagtXAERg1POpWj/DrTZjBlwQeabwrZZ7cm1Gcetcw3lMVWl6hipBaUymqKtUPk40jQpjkM7EEw/5YAR71yZdHBZnDIiXI6nkcpVVJZMeK8YnFsALD8bSjt208PXPXy1/1FDrS3LMX3B7f+XUy5eksi9X7M6d1JJS5zZEcfO8F4AZyRMQDImf58tb8/PliBF1X8IR+IgFyX+CwYl7e9jpB7yuLseyyV7L8rcJTtXMTMaIsnCmdRuRPAi+1FMRfVPVQY5VwyHNpCX7BZmG76utyB2p/3FMqNSZD8pF7sWJRCEmZtwENUsMx2OOmJAqS5ZNz8jP5Eje/wBZFyJWveYkROhLULOwjZupWrWrrnJ1MLJTy+GFVZD97N1rxhTc0tUQa8Bgo00n8PxPJf5+WIFGumA2HWucr8uaL5TQI9Q23at03o4q/KhTN6H3LG+z5QivHTAWcTBbZoKs/Tkasx6FhDUgAsNyFvakAuOa99x3SKZYKtcCECVOhK/dX5B
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: paperless-ngx-secret
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pg-paperless
spec:
  encryptedData:
    password: AgDeZ/6mehFIp2+Coyh4fcovIA9UBRuHZpCrBsnxPppC++w5tnfXmp2dhPIX49RS4CqxdPOqMrn56m5wQAPCo7Q2tRpjDauB77PPHtjik8NXHw0q4ZbXnyum2terBNZ8wqKjlp8GhJ2B6rn0Xu+0ZG89kFTgSFUiBmUzNiVCgv0RES3NyQoaKP+SSl4J/wAqCcbKpg//1Uu1d1YSCKjX13AVP0nkLXe15HxzVqHFxbAuIjylVNGL5oZs/M6SCH9XGjnyhh+Oz6B0Mk6Hmsqf8Oay+Qz6rr6TgSUVVTUCfmK9wtLTtq2Rhm6CfA8ruNFKdic6nUt9rsurxgMS0tp7B4g5BCF29fSO9ZyqjBo9r9ZnjMFxdcEXuGkwP36IH3wzKuTR9oFUE0xB/HyJIrN1veXLW9zD7WaIdRwNkXFLu/ZAxqPwJFKkppjNfWhDg+ALRPzCBoXMfHPKdzbN7sSFv558yxI3ACneZCryLZVT9MydecnAMRDeHN7HUhVrQYLkqo3p5rwsxJk0QWImNCh7VTIKeDeizFhbs6IUYOOb23tr66znTc425RC/kXJwJtHR834jrI4wrZA3qeWR256c13xlzYcl+fg3ldC5/xuOC4ac/JrIwqHca5TmDlzkgw2pG7YRLUzdSvWdWX5ulq43W8Hp8kAGm4kUb19RlY9GN3LnKumXrBiSUJJIl/ZUn0j+r06q6UANaP5A5pE0THY=
    username: AgCvueQie1kfmD2SVdOCF6y1KYzSfTETMgpP9NiQE8e9XrHegl+CWmSnv6CtaRtNB6zGiNMnE8QWZXjPIeahs2tEkTbNU2EWLHI6rPr3zwndAjBLDQT4i8DBVmwqffpy3leR+onzHgAYjuN1oYdaIoFA8B3KTmENu2PwdWKqlT1ne9KPnpkiwOKwTPp+TpCAdn4AMbd30uRNc5s0RHk3WFuMqDrgDqA+NqrmW8h6+JFMlHMOOkF8T5lrTEEtK3l2rzlKa6lhsaD8FF0OcXD6kwcSxjs9B8o3j4sGMmiKOREIBYTGscpPFGdsk5qVwc1h0fy7x4jNCZNjMYaLKG91ckXVy2ozqWzHe6nph8LhB8EuncKWKCeCjKd6Ye8SdBWVYvGM7N1joD7oDB4t5l6+P+Swhnni4dUwSMG3DKIzgflDHoo9ZCcUQTQUUL3e2DiIeKMctE10ipMk/73PJdbBmLeeEf42kipvGkE5cZjE+ZxNdl5xPIUTTHWl7OxqzO17C1Zj+8kX/pRYjy9Cso8kcEJC8cN6XgIb2pyCgsb+By2uHOitUmV45waS3F6X2Mf8DCNZgaZGDLTB8jcfC4Mwi6s/z2yEvfpzgSfcJoc7aqY3/HD4nNYZFmpldSia1ZfSnXLdDSvvnUJq58xh5hgwKXrJQLMrhHPZeBv6M1IhhIRO4YkGNLsas5ePRwAbnqwKM3OkCgpGgqV8Tuw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pg-paperless
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: paperless-ngx-oidc-config
spec:
  encryptedData:
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: AgAMkEb4c9derROM+kzJ9okpVka31SHasnY6yRrU7tpVCCbFq5EiqvSSZkGZezadDexciEHhJTcczCsz4HX9R9rtr51GXjWSjFAUf308wkItO1s1wpt9yf48PZqK9SywHoObChNP+H8mbpeTw8pl0zqPXrIoofkgFRK7UnNZ8E/wsNOQzIRH92+osTFdxp6Pa5+PH2hxZqhuSeNdrK0gTBfxm+hkHnpNlrBrvM36HlIpnt9lqqPDSHo8NRxurBWTAeOeRRC9eqaXiWTLVl9KfBn7KxY3QxntDsu6+Ik/YEKrRvJa+sk9e3EL6NUu5BKlq+EABlN4GRybZRjU2/0a7nuSD14jFHwmW0Zphkt7Ywxc4DWHDWkNNZ4R2m/bbo0PrDbmYB/tNrMs+FfvcsR5oZ0DdmmhX8qMWQObffj9cVQnBnNwIIR9Tcne5HCLznwQsAXEUtiuLLCNjhZaaXlyuS6EmLnGxk1IDWp8/ZV4ai0IZHDyA32MA0v2qKrabtRYIOp6bbm00+bzepbojIAMtmwpOpm9ZFXg/2687qCqkKhsgMQhoEjEKOzspzeyJfa9sjBHJGQDOpF/tvqQyM8BVO3GgI+HXgokKaKgDrO0qgSXmN39tlPZAInKIfejF1yc3D7UnwPITf5asoBPRcMxmErwDRB3fcjANKGckmvMp1C88mBGAMhaABm9NU5h+qyr/Z206lu7tqLb64xrv8lGY9oV6PjqRJ0ChM0dQN/nrVBSgJivewvkDbE5AbEip2DgNIv/jFr1g7kLMYnKD6ot3sRN3L72Ls3XsdDGZmevronWlZARbBdfKwY4M3+/08JKRvdG1yj9Yz3vhbbLnUZ5qsjUaLTbLnQwZDkxHrF0ozomRv1tHgakIxg8n+QovO6LY3F4tHdZ555FZiu65yJQuAVdrn+inVu0jWlyHyAJQZmbm79s1FLLnmHqC3/yoYOdWWDt9LmqUQstdeSZlyd23XZsNrypkLWkC8ae790au+yFBmGRiBVeeeZl4GQKqSJaFUzaT3+We5TZZws4PbgXtu+B8hdd0TIhyS6XsSvicxxajXBTkgA9n1pbC5VUEtOU3TOYlULLWuJfd6sRSQEpQk1WiWkUNQBPw87dwmXI+EEZGL5Ir+kdkXYqw2JH2lUKQ4v4AUlx1OpzdBxjryTfKZVgHPR1l4RRstpXMG4CpPbbKoi/S6DxZCZNVPXW8V4sYHYor3q3ybm3K3+GCksUZ2+wDcfEBeOSqw7rVSPG5AUwJe6VfUHS1ruCAj6Ejrb2cCcwOyABZrqZt+9fohvrQTW3lDJLrHBMYuGWh2Mmkm76XDF422j+5xF3PDxMsbnqao8Q3LYLCopV
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: paperless-ngx-oidc-config
