apiVersion: v1
kind: Service
metadata:
  labels:
    service: minecraft-server
  name: minecraft-server
spec:
  ports:
    - protocol: TCP
      name: minecraft
      port: 25565
      targetPort: 25565
      nodePort: 30565
  type: NodePort
  selector:
    app: minecraft-server
