apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-server
spec:
  replicas: 1
  serviceName: minecraft-server
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          envFrom:
            - configMapRef:
                name: minecraft-server-cm
                optional: true
          env: []
          image: itzg/minecraft-server
          ports:
            - containerPort: 25565
              name: minecraft
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /data
              name: minecraft-server-data
          resources:
            requests:
              cpu: 150m
              memory: 4Gi
            limits:
              memory: 4Gi
          livenessProbe:
            exec:
              command: ["mc-health"]
            initialDelaySeconds: 120
            periodSeconds: 60
          readinessProbe:
            exec:
              command: ["mc-health"]
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 12
  volumeClaimTemplates:
    - metadata:
        name: minecraft-server-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
